services:
  discord-bot:
    image: ghcr.io/gamedirection/open-trivia-discord:latest
    env_file:
      - .env
    volumes:
      - bot_state:/tmp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  bot_state:
